/* Product data extracted precisely from CRACKERS PRICE LIST - 2026 */
const products = [
    { id: "1", category: "Sky Riders", name: "CHOTTA SKYSHOT", actualPrice: 100, discountPrice: 50, pack: "1 Piece" },
    { id: "2", category: "Sky Riders", name: "MINI CHOTTA SKYSHOT", actualPrice: 40, discountPrice: 20, pack: "1 Piece" },
    { id: "3", category: "Sky Riders", name: "2 SOUND", actualPrice: 60, discountPrice: 30, pack: "1 Packet" },
    { id: "4", category: "Sky Riders", name: "3 SOUND", actualPrice: 80, discountPrice: 40, pack: "1 Packet" },
    { id: "5", category: "Sky Riders", name: "AIR RIDER", actualPrice: 40, discountPrice: 20, pack: "1 Box" },
    { id: "6", category: "Sky Riders", name: "SKYSHOT", actualPrice: 40, discountPrice: 20, pack: "1 Piece" },
    { id: "7", category: "Sky Riders", name: "2\" FANCY", actualPrice: 240, discountPrice: 120, pack: "1 Piece" },
    { id: "8", category: "Sky Riders", name: "3\" FANCY", actualPrice: 440, discountPrice: 220, pack: "1 Piece" },
    { id: "9", category: "Sky Riders", name: "3½\" FANCY", actualPrice: 560, discountPrice: 280, pack: "1 Piece" },
    { id: "10", category: "Sky Riders", name: "3 PIECE FANCY", actualPrice: 560, discountPrice: 280, pack: "1 Box" },
    { id: "11", category: "Sky Riders", name: "DOUBLE BALL FANCY", actualPrice: 720, discountPrice: 360, pack: "1 Box" },
    { id: "12", category: "Sky Riders", name: "BABY ROCKET", actualPrice: 80, discountPrice: 40, pack: "1 Box" },
    { id: "13", category: "Sky Riders", name: "ROCKET BOMB", actualPrice: 110, discountPrice: 55, pack: "1 Box" },
    { id: "14", category: "Sky Riders", name: "2\" S ROCKET", actualPrice: 180, discountPrice: 90, pack: "1 Box" },
    { id: "15", category: "Sky Riders", name: "3\" S ROCKET", actualPrice: 190, discountPrice: 95, pack: "1 Box" },
    { id: "16", category: "Sky Riders", name: "LUNIC ROCKET", actualPrice: 200, discountPrice: 100, pack: "1 Box" },
    { id: "17", category: "Sky Riders", name: "DRONE", actualPrice: 300, discountPrice: 150, pack: "1 Box" },
    { id: "18", category: "Sky Riders", name: "HELICOPTER", actualPrice: 200, discountPrice: 100, pack: "1 Box" },
    { id: "19", category: "Multiple Skyriders", name: "7 SHOT", actualPrice: 50, discountPrice: 25, pack: "1 Piece" },
    { id: "20", category: "Multiple Skyriders", name: "12 SHOT", actualPrice: 320, discountPrice: 160, pack: "1 Piece" },
    { id: "21", category: "Multiple Skyriders", name: "15 SHOT", actualPrice: 720, discountPrice: 360, pack: "1 Piece" },
    { id: "22", category: "Multiple Skyriders", name: "30 SHOT", actualPrice: 840, discountPrice: 420, pack: "1 Piece" },
    { id: "23", category: "Multiple Skyriders", name: "60 SHOT", actualPrice: 1640, discountPrice: 820, pack: "1 Piece" },
    { id: "24", category: "Multiple Skyriders", name: "120 SHOT", actualPrice: 3600, discountPrice: 1800, pack: "1 Piece" },
    { id: "25", category: "Multiple Skyriders", name: "240 SHOT", actualPrice: 6800, discountPrice: 3400, pack: "1 Piece" },
    { id: "26", category: "Hand Sparklers", name: "7CM SPARKLERS", actualPrice: 30, discountPrice: 15, pack: "1 Box" },
    { id: "27", category: "Hand Sparklers", name: "7CM COLOUR SPARKLERS", actualPrice: 30, discountPrice: 15, pack: "1 Box" },
    { id: "28", category: "Hand Sparklers", name: "10CM SPARKLERS", actualPrice: 50, discountPrice: 25, pack: "1 Box" },
    { id: "29", category: "Hand Sparklers", name: "10CM COLOUR SPARKLERS", actualPrice: 50, discountPrice: 25, pack: "1 Box" },
    { id: "30", category: "Hand Sparklers", name: "15CM SPARKLERS", actualPrice: 100, discountPrice: 50, pack: "1 Box" },
    { id: "31", category: "Hand Sparklers", name: "15CM COLOUR SPARKLERS", actualPrice: 100, discountPrice: 50, pack: "1 Box" },
    { id: "32", category: "Hand Sparklers", name: "30CM SPARKLERS", actualPrice: 120, discountPrice: 60, pack: "1 Box" },
    { id: "33", category: "Hand Sparklers", name: "30CM COLOUR SPARKLERS", actualPrice: 120, discountPrice: 60, pack: "1 Box" },
    { id: "34", category: "Hand Sparklers", name: "50CM SPARKLERS", actualPrice: 320, discountPrice: 160, pack: "1 Box" },
    { id: "35", category: "Hand Sparklers", name: "THUNDER PENCIL", actualPrice: 320, discountPrice: 160, pack: "1 Box" },
    { id: "36", category: "Hand Sparklers", name: "BURFI PENCIL", actualPrice: 180, discountPrice: 90, pack: "1 Box" },
    { id: "37", category: "Hand Sparklers", name: "50/50 PENCIL", actualPrice: 280, discountPrice: 140, pack: "1 Box" },
    { id: "38", category: "Hand Sparklers", name: "1½ FEET SATTAI", actualPrice: 60, discountPrice: 30, pack: "1 Box" },
    { id: "39", category: "Hand Sparklers", name: "4 FEET SATTAI", actualPrice: 120, discountPrice: 60, pack: "1 Box" },
    { id: "40", category: "Hand Sparklers", name: "SELFIE STICK", actualPrice: 240, discountPrice: 120, pack: "1 Box" },
    { id: "41", category: "Hand Sparklers", name: "LOLLIPOP", actualPrice: 400, discountPrice: 200, pack: "1 Box" },
    { id: "42", category: "Hand Sparklers", name: "RAINBOW FOG", actualPrice: 320, discountPrice: 160, pack: "1 Box" },
    { id: "43", category: "Flower Pots", name: "FLOWER POT SMALL", actualPrice: 100, discountPrice: 50, pack: "1 Box" },
    { id: "44", category: "Flower Pots", name: "FLOWER POT BIG", actualPrice: 120, discountPrice: 60, pack: "1 Box" },
    { id: "45", category: "Flower Pots", name: "FLOWER POT SPECIAL", actualPrice: 140, discountPrice: 70, pack: "1 Box" },
    { id: "46", category: "Flower Pots", name: "FLOWER POT ASHOKA", actualPrice: 160, discountPrice: 80, pack: "1 Box" },
    { id: "47", category: "Flower Pots", name: "FLOWER POT SUPER", actualPrice: 260, discountPrice: 130, pack: "1 Box" },
    { id: "48", category: "Flower Pots", name: "FLOWER POT DELUXE", actualPrice: 280, discountPrice: 140, pack: "1 Box" },
    { id: "49", category: "Flower Pots", name: "FLOWER POT (COLOUR)", actualPrice: 320, discountPrice: 160, pack: "1 Box" },
    { id: "50", category: "Magical Spinner", name: "SPINNER", actualPrice: 150, discountPrice: 75, pack: "1 Box" },
    { id: "51", category: "Magical Spinner", name: "DISCO WHEEL", actualPrice: 240, discountPrice: 120, pack: "1 Box" },
    { id: "52", category: "Magical Spinner", name: "BIG CHAKRA", actualPrice: 80, discountPrice: 40, pack: "1 Box" },
    { id: "53", category: "Magical Spinner", name: "SPECIAL CHAKRA", actualPrice: 140, discountPrice: 70, pack: "1 Box" },
    { id: "54", category: "Magical Spinner", name: "DELUXE CHAKARA", actualPrice: 240, discountPrice: 120, pack: "1 Box" },
    { id: "55", category: "Magical Spinner", name: "BUTTERFLY", actualPrice: 180, discountPrice: 90, pack: "1 Box" },
    { id: "56", category: "Magical Spinner", name: "LOTUS", actualPrice: 280, discountPrice: 140, pack: "1 Box" },
    { id: "57", category: "Kids World", name: "PHOTO FLASH", actualPrice: 240, discountPrice: 120, pack: "1 Box" },
    { id: "58", category: "Kids World", name: "CHITPUT", actualPrice: 50, discountPrice: 25, pack: "1 Box" },
    { id: "59", category: "Kids World", name: "STONE", actualPrice: 40, discountPrice: 20, pack: "1 Box" },
    { id: "60", category: "Kids World", name: "ROLL CAP", actualPrice: 90, discountPrice: 45, pack: "1 Box" },
    { id: "61", category: "Kids World", name: "SNAKE", actualPrice: 80, discountPrice: 40, pack: "1 Box" },
    { id: "62", category: "Kids World", name: "BAT & BALL", actualPrice: 400, discountPrice: 200, pack: "1 Box" },
    { id: "63", category: "Kids World", name: "CARTOON", actualPrice: 50, discountPrice: 25, pack: "1 Box" },
    { id: "64", category: "Kids World", name: "OSTRICH", actualPrice: 360, discountPrice: 180, pack: "1 Box" },
    { id: "65", category: "Kids World", name: "CAR", actualPrice: 480, discountPrice: 240, pack: "1 Box" },
    { id: "66", category: "Kids World", name: "SUPER SINGER", actualPrice: 240, discountPrice: 120, pack: "1 Box" },
    { id: "67", category: "Kids World", name: "FANCY FOUNTAIN", actualPrice: 300, discountPrice: 150, pack: "1 Piece" },
    { id: "68", category: "Kids World", name: "PEACOCK FEATHER", actualPrice: 220, discountPrice: 110, pack: "1 Piece" },
    { id: "69", category: "Kids World", name: "PEACOCK BIG", actualPrice: 840, discountPrice: 420, pack: "1 Piece" },
    { id: "70", category: "Kids World", name: "TRI COLOUR", actualPrice: 480, discountPrice: 240, pack: "1 Box" },
    { id: "71", category: "Kids World", name: "STAR RAIN", actualPrice: 420, discountPrice: 210, pack: "1 Box" },
    { id: "72", category: "Kids World", name: "SIREN", actualPrice: 320, discountPrice: 160, pack: "1 Box" },
    { id: "73", category: "Kids World", name: "GOLDEN GLOBE", actualPrice: 220, discountPrice: 110, pack: "1 Box" },
    { id: "74", category: "Kids World", name: "COLOUR RAIN", actualPrice: 240, discountPrice: 120, pack: "1 Box" },
    { id: "75", category: "Kids World", name: "SING POP", actualPrice: 320, discountPrice: 160, pack: "1 Box" },
    { id: "76", category: "Kids World", name: "FOX STAR", actualPrice: 280, discountPrice: 140, pack: "1 Box" },
    { id: "77", category: "Kids World", name: "KURKURAY", actualPrice: 520, discountPrice: 260, pack: "1 Box" },
    { id: "78", category: "Kids World", name: "BALAE BALAE", actualPrice: 400, discountPrice: 200, pack: "1 Box" },
    { id: "79", category: "Kids World", name: "ASURAPIE", actualPrice: 280, discountPrice: 140, pack: "1 Box" },
    { id: "80", category: "Sound Blaster", name: "50 BIGILI", actualPrice: 50, discountPrice: 25, pack: "1 Packet" },
    { id: "81", category: "Sound Blaster", name: "100 BIGILI", actualPrice: 80, discountPrice: 40, pack: "1 Packet" },
    { id: "82", category: "Sound Blaster", name: "234 KURUVI", actualPrice: 20, discountPrice: 10, pack: "1 Packet" },
    { id: "83", category: "Sound Blaster", name: "4\" GOLD LAKSHMI", actualPrice: 80, discountPrice: 40, pack: "1 Packet" },
    { id: "84", category: "Sound Blaster", name: "4\" LAKSHMI DELUXE", actualPrice: 60, discountPrice: 30, pack: "1 Packet" },
    { id: "85", category: "Sound Blaster", name: "4\" LAKSHMI", actualPrice: 50, discountPrice: 25, pack: "1 Packet" },
    { id: "86", category: "Sound Blaster", name: "32 LAKSHMI", actualPrice: 40, discountPrice: 20, pack: "1 Packet" },
    { id: "87", category: "Sound Blaster", name: "ATOM BOMB", actualPrice: 120, discountPrice: 60, pack: "1 Box" },
    { id: "88", category: "Sound Blaster", name: "HYDRO BOMB", actualPrice: 140, discountPrice: 70, pack: "1 Box" },
    { id: "89", category: "Sound Blaster", name: "SUPER BOMB", actualPrice: 180, discountPrice: 90, pack: "1 Box" },
    { id: "90", category: "Sound Blaster", name: "CLASSIC BOMB", actualPrice: 220, discountPrice: 110, pack: "1 Box" },
    { id: "91", category: "Sound Blaster", name: "JURASSIC BOMB", actualPrice: 360, discountPrice: 180, pack: "1 Box" },
    { id: "92", category: "Sound Blaster", name: "BULLET BOMB", actualPrice: 60, discountPrice: 30, pack: "1 Box" },
    { id: "93", category: "Sound Blaster", name: "555 TIMING BOMB", actualPrice: 260, discountPrice: 130, pack: "1 Box" },
    { id: "94", category: "Sound Blaster", name: "TERRIBLE BOMB", actualPrice: 520, discountPrice: 260, pack: "1 Box" },
    { id: "95", category: "Paper Sound Blaster", name: "1/4KG PAPER BOMB", actualPrice: 150, discountPrice: 75, pack: "1 Box" },
    { id: "96", category: "Paper Sound Blaster", name: "1/2KG PAPER BOMB", actualPrice: 280, discountPrice: 140, pack: "1 Box" },
    { id: "97", category: "Paper Sound Blaster", name: "1KG PAPER BOMB", actualPrice: 560, discountPrice: 280, pack: "1 Box" },
    { id: "98", category: "Paper Sound Blaster", name: "2KG PAPER BOMB", actualPrice: 680, discountPrice: 340, pack: "1 Box" },
    { id: "99", category: "Paper Sound Blaster", name: "MONEY BANK BOMB", actualPrice: 420, discountPrice: 210, pack: "1 Box" },
    { id: "100", category: "Paper Sound Blaster", name: "10 in 1 PAPER BOMB", actualPrice: 500, discountPrice: 250, pack: "1 Box" },
    { id: "101", category: "Multiple Sound Blaster", name: "100 WAALA", actualPrice: 100, discountPrice: 50, pack: "1 Box" },
    { id: "102", category: "Multiple Sound Blaster", name: "200 WAALA", actualPrice: 150, discountPrice: 75, pack: "1 Box" },
    { id: "103", category: "Multiple Sound Blaster", name: "300 WAALA", actualPrice: 200, discountPrice: 100, pack: "1 Box" },
    { id: "104", category: "Multiple Sound Blaster", name: "600 WAALA", actualPrice: 350, discountPrice: 175, pack: "1 Box" },
    { id: "105", category: "Multiple Sound Blaster", name: "1000 WAALA", actualPrice: 500, discountPrice: 250, pack: "1 Box" },
    { id: "106", category: "Multiple Sound Blaster", name: "2000 WAALA", actualPrice: 1000, discountPrice: 500, pack: "1 Box" },
    { id: "107", category: "Multiple Sound Blaster", name: "5000 WAALA", actualPrice: 2400, discountPrice: 1200, pack: "1 Box" },
    { id: "108", category: "Multiple Sound Blaster", name: "10000 WAALA", actualPrice: 4600, discountPrice: 2300, pack: "1 Box" },
    { id: "109", category: "Multiple Sound Blaster", name: "28 WAALA", actualPrice: 30, discountPrice: 15, pack: "1 Packet" },
    { id: "110", category: "Multiple Sound Blaster", name: "28 GIANT WAALA", actualPrice: 50, discountPrice: 25, pack: "1 Packet" },
    { id: "111", category: "Multiple Sound Blaster", name: "24 DELUXE WAALA", actualPrice: 90, discountPrice: 45, pack: "1 Packet" },
    { id: "112", category: "Multiple Sound Blaster", name: "50 DELUXE WAALA", actualPrice: 200, discountPrice: 100, pack: "1 Packet" },
    { id: "113", category: "Multiple Sound Blaster", name: "100 DELUXE WAALA", actualPrice: 360, discountPrice: 180, pack: "1 Packet" }
];
